# Generated by Django 4.2.5 on 2023-09-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='progress',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
